#!/usr/bin/env bash
# script to transfer a file from our client to a server

# check that at least 3 arguments have been provided
if [ "$#" -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME"
else
    scp -o StrictHostKeyChecking=no -i ~/.ssh/school "$1" "$3@$2:~/"
fi
